### ISSUE TITLE
Integrate kubectl-neat to kubectl-get upstream?

### ISSUE THREAD

**Issue by tringuyen-yw** [itaysk/kubectl-neat#34]
Hi,

Thank you very much for this plugin. This is more of a question/request than an issue.

Would it make more sense to integrate the functionality of `kubectl-neat` to upstream `kubectl get`? In my opinion, `kubectl-neat` is the solution to this [kubernetes issue 90066: managedFields options are very verbose](https://github.com/kubernetes/kubernetes/issues/90066)

**Comment by itaysk** [comment]
Hi, thanks for your interest in kubectl-neat. I'd love to contribute in any way that the kubectl folks like, but I'm sure that if they wanted to remove `mangedField` from the UX, they would have found a better, simpler way to do that. Since kubectl-neat is doing much more things (like removing defaults, and controller managed fields), it might be an overkill for just that problem. I think that before looking for technical solutions, a decision needs to be made over at "kubernetes", and so far they have been very clear about not wanting to intervene in this case. 
Let me know if I can help in any way you think is helpful, and keep the feedback coming :)
